IF OBJECT_ID('dbo.TRANSACAO', 'U') IS NOT NULL DROP TABLE dbo.TRANSACAO;
IF OBJECT_ID('dbo.CLIENTE', 'U') IS NOT NULL DROP TABLE dbo.CLIENTE;

CREATE TABLE dbo.CLIENTE (
    Id            INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_CLIENTE PRIMARY KEY,
    Nome          NVARCHAR(100)     NOT NULL,
    Email         NVARCHAR(150)     NOT NULL CONSTRAINT UQ_CLIENTE_EMAIL UNIQUE,
    Telefone      NVARCHAR(20)      NULL,
    DataCadastro  DATETIME2         NOT NULL CONSTRAINT DF_CLIENTE_DATA DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.TRANSACAO (
    Id             INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TRANSACAO PRIMARY KEY,
    ClienteId      INT               NOT NULL,
    Descricao      NVARCHAR(200)     NOT NULL,
    Valor          DECIMAL(18,2)     NOT NULL CONSTRAINT CK_TRANSACAO_VALOR CHECK (Valor > 0),
    Tipo           VARCHAR(20)       NOT NULL CONSTRAINT CK_TRANSACAO_TIPO CHECK (Tipo IN ('PIX','BOLETO','CARTAO')),
    Status         VARCHAR(20)       NOT NULL CONSTRAINT DF_TRANSACAO_STATUS DEFAULT 'PENDENTE'
                   CONSTRAINT CK_TRANSACAO_STATUS CHECK (Status IN ('PENDENTE','PAGO','CANCELADO')),
    DataTransacao  DATETIME2         NOT NULL CONSTRAINT DF_TRANSACAO_DATA DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_TRANSACAO_CLIENTE FOREIGN KEY (ClienteId) REFERENCES dbo.CLIENTE(Id) ON DELETE CASCADE
);

CREATE INDEX IX_TRANSACAO_CLIENTE ON dbo.TRANSACAO(ClienteId);
